return {models={
 ["original"]="/Game/Vehicles/Weapons/w_msl_a0/Model/SM_w_msl_a0.SM_w_msl_a0",
 ["qaam"]="/Game/Vehicles/Weapons/w_qaam_a0/Model/SM_w_qaam_a0.SM_w_qaam_a0",
 ["sasm"]="/Game/Vehicles/Weapons/w_sasm_a0/Model/SM_w_sasm_a0.SM_w_sasm_a0",
},planes={
 ["BP_PlayerPlane_PP0001_a10c_C"]={variant="BP_plwp_msl_a0_C",model="qaam" },
 ["BP_PlayerPlane_PP0002_f02a_C"]={variant="BP_plwp_msl_j0_C",model="original" },
 ["BP_PlayerPlane_PP0003_f04e_C"]={variant="BP_plwp_msl_a0_C",model="original" },
 ["BP_PlayerPlane_PP0004_f15c_C"]={variant="BP_plwp_msl_a0_C",model="qaam" },
 ["BP_PlayerPlane_PP0005_f22a_C"]={variant="BP_plwp_msl_a0_C",model="qaam" },
 ["BP_PlayerPlane_PP0006_f35c_C"]={variant="BP_plwp_msl_a1_C",model="qaam" },
 ["BP_PlayerPlane_PP0007_f18c_C"]={variant="BP_plwp_msl_a0_C",model="qaam" },
 ["BP_PlayerPlane_PP0008_j39e_C"]={variant="BP_plwp_msl_a0_C",model="sasm" },
 ["BP_PlayerPlane_PP0009_su34_C"]={variant="BP_plwp_msl_r0_C",model="original" },
 ["BP_PlayerPlane_PP0010_e18g_C"]={variant="BP_plwp_msl_a0_C",model="qaam" },
 ["BP_PlayerPlane_PP0011_typn_C"]={variant="BP_plwp_msl_a0_C",model="sasm" },
 ["BP_PlayerPlane_PP0012_f15j_C"]={variant="BP_plwp_msl_j0_C",model="original" },
 ["BP_PlayerPlane_PP0013_a06e_C"]={variant="BP_plwp_msl_a0_C",model="original" },
 ["BP_PlayerPlane_PP0013_a06e_ms15_C"]={variant="BP_plwp_msl_a0_C",model="original" },
 ["BP_PlayerPlane_PP0014_rflm_C"]={variant="BP_plwp_msl_f0_C",model="original" },
 ["BP_PlayerPlane_PP0015_su25_C"]={variant="BP_plwp_msl_r0_C",model="original" },
 ["BP_PlayerPlane_PP0016_x40a_C"]={variant="BP_plwp_msl_a1_C",model="qaam" },
 ["BP_PlayerPlane_PP0017_mr2k_C"]={variant="BP_plwp_msl_f0_C",model="original" },
 ["BP_PlayerPlane_PP0018_fa36_C"]={variant="BP_plwp_msl_a1_C",model="qaam" },
 ["BP_PlayerPlane_PP0019_ea36_C"]={variant="BP_plwp_msl_a1_C",model="qaam" },
 ["BP_PlayerPlane_PP0020_m29a_C"]={variant="BP_plwp_msl_r0_C",model="original" },
 ["BP_PlayerPlane_PP0021_su57_C"]={variant="BP_plwp_msl_r0_C",model="original" },
 ["BP_PlayerPlane_PP0022_f16c_C"]={variant="BP_plwp_msl_a0_C",model="qaam" },
 ["BP_PlayerPlane_PP0023_f14d_C"]={variant="BP_plwp_msl_a0_C",model="original" },
 ["BP_PlayerPlane_PP0024_f18f_C"]={variant="BP_plwp_msl_a0_C",model="qaam" },
 ["BP_PlayerPlane_PP0024_f18f_ms01_C"]={variant="BP_plwp_msl_a0_C",model="qaam" },
 ["BP_PlayerPlane_PP0025_f15e_C"]={variant="BP_plwp_msl_a0_C",model="qaam" },
 ["BP_PlayerPlane_PP0026_su47_C"]={variant="BP_plwp_msl_r0_C",model="original" },
 ["BP_PlayerPlane_PP0027_m21b_C"]={variant="BP_plwp_msl_r0_C",model="original" },
 ["BP_PlayerPlane_PP0028_su35_C"]={variant="BP_plwp_msl_r0_C",model="original" },
 ["BP_PlayerPlane_PP0029_m31b_C"]={variant="BP_plwp_msl_r0_C",model="original" },
 ["BP_PlayerPlane_PP0030_su33_C"]={variant="BP_plwp_msl_r0_C",model="original" },
 ["BP_PlayerPlane_PP0031_e06b_C"]={variant="BP_plwp_msl_a0_C",model="original" },
 ["BP_PlayerPlane_PP0032_f18e_C"]={variant="BP_plwp_msl_a0_C",model="qaam" },
 ["BP_PlayerPlane_PP0034_f14a_C"]={variant="BP_plwp_msl_a0_C",model="original" },
 ["BP_PlayerPlane_PP0038_adfx02_L001_C"]={variant="BP_plwp_msl_a0_C",model="qaam" },
}}
