@echo off
cd /d "%~dp0"
call build.cmd
if errorlevel 1 exit /b 1
python run-checked-tests.py peace_agile_tests peace_agile_joint_tests peace_agile_runtime_tests peace_agile_closedloop_tests recorder_tests modes_tests fullmodel_tests agility_tests control_timing_tests observation_tests custom_keys_tests capture_runtime_tests capture_adaptation_tests camera_context_tests cutscene_recovery_tests hud_reference_tests takeover_logic_tests leveling_tests plane_tests native_hud_snapshot_tests hybrid_hud_tests hud_prediction_tests hud_interpolation_tests helmet_tests
exit /b %errorlevel%
