"""Generate GPU overlay tokens from the packaged CreeperUX kit; no runtime JSON reads."""
from pathlib import Path
import json,re,argparse
root=Path(__file__).resolve().parents[1]
tokens=json.loads((root/'package-template/ui/creeperux/tokens.json').read_text())
lines=['// Generated by scripts/generate-hud-theme.py. Edit CreeperUX tokens, not this file.', '#pragma once', 'namespace creeperux {']
for name,values in tokens['color'].items():
 value=values['dark']
 if value.startswith('#'):rgba=[int(value[i:i+2],16)/255 for i in (1,3,5)]+[1]
 elif value.startswith('rgba'):rgba=[float(v.strip()) for v in value[5:-1].split(',')];rgba[:3]=[v/255 for v in rgba[:3]]
 else:continue
 lines.append('inline const D2D1_COLOR_F '+name.replace('-','_')+'={'+','.join(f'{v:.8f}f' for v in rgba)+'};')
for name in ('panel','control','chip'):lines.append(f'inline constexpr float radius_{name}={float(tokens["radius"][name][:-2]):.1f}f;')
for name,size in tokens['type'].items():
 if size.endswith('px'):lines.append(f'inline constexpr float type_{name.replace("2xl","xxl")}={float(size[:-2]):.1f}f;')
lines.append(f'inline constexpr float notice_exit={tokens["motion"]["roles"]["exit"]["d"]}f;')
lines.extend(['}', ''])
text='\n'.join(lines);out=root/'native/src/creeperux_tokens.h'
p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
if args.check:assert out.read_text()==text,'GPU UI tokens drifted; run generate-hud-theme.py'
else:out.write_text(text)
print('PASS GPU UI tokens match CreeperUX kit')
