#pragma once
// Generated by analysis/make_aircraft_table.py from 60 archived AC8 flight logs (721k frames).
// Multi-step 0.5 s window fits; gains are scales on the shared prior at the flown speed;
// estimates shrunk toward the pooled value by sample size. push = push/pull authority ratio.
namespace ac8_models {
struct Axis {float tau,delay,scale;};
struct Aircraft {int id;Axis pitch,roll,yaw;float push;bool known;};
inline constexpr Aircraft table[]={
 {4010,{1.012f,0.180f,0.961f},{0.923f,0.122f,0.891f},{0.662f,0.000f,0.857f},0.747f,true},
 {5010,{0.960f,0.167f,0.952f},{0.852f,0.120f,0.918f},{0.564f,0.000f,0.840f},0.731f,true},
 {6010,{1.143f,0.177f,0.935f},{0.945f,0.128f,0.887f},{0.545f,0.000f,0.971f},0.680f,true},
 {8010,{1.253f,0.191f,0.985f},{0.775f,0.105f,0.844f},{0.664f,0.000f,0.999f},0.706f,true},
 {10010,{1.078f,0.199f,0.980f},{0.935f,0.128f,0.917f},{0.600f,0.001f,0.945f},0.662f,true},
 {11010,{1.024f,0.173f,1.073f},{0.993f,0.128f,0.993f},{0.622f,0.000f,0.854f},0.742f,true},
 {12010,{1.038f,0.189f,0.926f},{0.876f,0.124f,0.861f},{0.687f,0.001f,0.908f},0.698f,true},
 {13010,{1.201f,0.231f,0.875f},{1.133f,0.143f,0.725f},{0.811f,0.005f,0.804f},0.625f,true},
 {14010,{1.222f,0.204f,1.019f},{1.144f,0.152f,0.958f},{0.631f,0.000f,1.049f},0.631f,true},
 {18010,{0.842f,0.150f,0.870f},{0.590f,0.098f,0.839f},{0.612f,0.000f,0.917f},0.801f,true},
 {20010,{1.069f,0.193f,0.958f},{0.854f,0.125f,0.851f},{0.643f,0.001f,0.905f},0.679f,true},
 {23010,{1.030f,0.195f,0.918f},{0.853f,0.124f,0.841f},{0.751f,0.001f,0.867f},0.682f,true},
 {24010,{1.079f,0.170f,0.913f},{0.811f,0.120f,0.832f},{0.583f,0.001f,0.915f},0.666f,true},
 {25010,{1.000f,0.182f,0.929f},{0.565f,0.099f,0.748f},{0.620f,0.003f,0.982f},0.742f,true},
 {28010,{1.011f,0.188f,0.973f},{0.776f,0.115f,0.877f},{0.633f,0.001f,0.987f},0.714f,true},
 {32010,{0.623f,0.276f,0.779f},{0.732f,0.120f,0.779f},{0.445f,0.000f,0.872f},0.426f,true},
};
// Unknown aircraft: pooled response, conservative (10th percentile) push ratio.
inline constexpr Aircraft pooled{-1,{1.046f,0.194f,0.950f},{0.854f,0.121f,0.863f},{0.620f,0.001f,0.928f},0.551f,false};
inline const Aircraft& find(int id){for(auto& a:table)if(a.id==id)return a;return pooled;}
}
