// Generated by scripts/generate-hud-theme.py. Edit CreeperUX tokens, not this file.
#pragma once
namespace creeperux {
inline const D2D1_COLOR_F bg={0.05098039f,0.06666667f,0.07843137f,1.00000000f};
inline const D2D1_COLOR_F deep={0.03529412f,0.05098039f,0.06274510f,1.00000000f};
inline const D2D1_COLOR_F panel={0.08235294f,0.10588235f,0.12156863f,1.00000000f};
inline const D2D1_COLOR_F raised={0.10588235f,0.13333333f,0.15294118f,1.00000000f};
inline const D2D1_COLOR_F hover={0.12549020f,0.15294118f,0.16862745f,1.00000000f};
inline const D2D1_COLOR_F text={0.95686275f,0.94509804f,0.92156863f,1.00000000f};
inline const D2D1_COLOR_F muted={0.66274510f,0.69019608f,0.70196078f,1.00000000f};
inline const D2D1_COLOR_F quiet={0.51372549f,0.56862745f,0.58823529f,1.00000000f};
inline const D2D1_COLOR_F line={0.93725490f,0.92156863f,0.89803922f,0.14000000f};
inline const D2D1_COLOR_F faint={0.93725490f,0.92156863f,0.89803922f,0.07000000f};
inline const D2D1_COLOR_F control={0.21568627f,0.21568627f,0.21568627f,1.00000000f};
inline const D2D1_COLOR_F boundary={0.41960784f,0.46274510f,0.48627451f,1.00000000f};
inline const D2D1_COLOR_F accent={0.97254902f,0.71764706f,0.00000000f,1.00000000f};
inline const D2D1_COLOR_F accent_hi={1.00000000f,0.77254902f,0.13333333f,1.00000000f};
inline const D2D1_COLOR_F accent_text={0.97254902f,0.71764706f,0.00000000f,1.00000000f};
inline const D2D1_COLOR_F accent_mark={0.97254902f,0.71764706f,0.00000000f,1.00000000f};
inline const D2D1_COLOR_F on_accent={0.06666667f,0.07843137f,0.08627451f,1.00000000f};
inline const D2D1_COLOR_F accent_soft={0.97254902f,0.71764706f,0.00000000f,0.12000000f};
inline const D2D1_COLOR_F focus={0.97254902f,0.71764706f,0.00000000f,1.00000000f};
inline const D2D1_COLOR_F info={0.39215686f,0.59215686f,0.65490196f,1.00000000f};
inline const D2D1_COLOR_F good={0.50196078f,0.67058824f,0.61960784f,1.00000000f};
inline const D2D1_COLOR_F bad={0.75686275f,0.52941176f,0.48627451f,1.00000000f};
inline const D2D1_COLOR_F warn={0.85098039f,0.64313725f,0.25490196f,1.00000000f};
inline const D2D1_COLOR_F scrim={0.01176471f,0.01960784f,0.02352941f,0.55000000f};
inline constexpr float radius_panel=6.0f;
inline constexpr float radius_control=5.0f;
inline constexpr float radius_chip=4.0f;
inline constexpr float type_xs=11.0f;
inline constexpr float type_sm=12.0f;
inline constexpr float type_md=13.0f;
inline constexpr float type_lg=14.0f;
inline constexpr float type_xl=17.0f;
inline constexpr float type_xxl=22.0f;
inline constexpr float notice_exit=0.09f;
}
